### ISSUE TITLE
This hta file is not copied from MDUT?

### ISSUE THREAD

**Issue by NKingpp** [Anonymous-ghost/LiqunKit_1.5_startup.hta_shellcode#1]
https://github.com/SafeGroceryStore/MDUT

**Comment by Anonymous-ghost** [comment]
I don't know . this hta file from&nbsp;https://github.com/Liqunkit/LiqunKit_


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Anonymous-ghost/LiqunKit_1.5_startup.hta_shellcode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 中午11:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Anonymous-ghost/LiqunKit_1.5_startup.hta_shellcode] This hta file is not copied from MDUT? (Issue #1)





 
https://github.com/SafeGroceryStore/MDUT
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NKingpp** [comment]
It's just a misunderstanding.
<img width="789" alt="image" src="https://user-images.githubusercontent.com/27681113/144175077-476ff4e2-d47d-4fe1-a28e-0dad607f3851.png">

**Comment by Anonymous-ghost** [comment]
so........
